# Generated by Django 4.2.11 on 2026-05-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("jira_filter_id", models.CharField(max_length=255)),
                (
                    "snapshot_time",
                    models.TimeField(help_text="Time to take snapshot (HH:MM format)"),
                ),
                (
                    "report_time",
                    models.TimeField(
                        help_text="Time to generate and send report (HH:MM format)"
                    ),
                ),
                ("admin_email", models.EmailField(max_length=254)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=100)),
                ("assignee", models.CharField(max_length=255)),
                ("eta", models.CharField(blank=True, max_length=255, null=True)),
                ("update_note", models.TextField(blank=True)),
                ("blockers", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket_id", "submitted_at"],
                        name="core_ticket_ticket__d25ae1_idx",
                    ),
                    models.Index(
                        fields=["assignee", "submitted_at"],
                        name="core_ticket_assigne_dc1d67_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("assignee", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=100)),
                ("priority", models.CharField(default="Medium", max_length=50)),
                ("updated", models.DateTimeField()),
                ("snapshot_date", models.DateField()),
                ("snapshot_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.filter",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["filter", "snapshot_date"],
                        name="core_ticket_filter__422917_idx",
                    ),
                    models.Index(
                        fields=["ticket_id", "snapshot_date"],
                        name="core_ticket_ticket__3d4918_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SnapshotComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comparison_date", models.DateField()),
                ("new_tickets", models.JSONField(default=list)),
                ("removed_tickets", models.JSONField(default=list)),
                ("status_changes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="core.filter",
                    ),
                ),
            ],
            options={
                "ordering": ["-comparison_date"],
                "indexes": [
                    models.Index(
                        fields=["filter", "comparison_date"],
                        name="core_snapsh_filter__45ee2d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignee_email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=500, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to="core.filter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="core_emailt_token_c7ba5b_idx"),
                    models.Index(
                        fields=["expires_at"], name="core_emailt_expires_bb7459_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("markdown_content", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.filter",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["filter", "report_date"],
                        name="core_dailyr_filter__2eabb2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analytics_date", models.DateField()),
                ("total_tickets", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("missed_count", models.IntegerField(default=0)),
                ("new_tickets_count", models.IntegerField(default=0)),
                ("resolved_count", models.IntegerField(default=0)),
                ("assignee_metrics", models.JSONField(default=dict)),
                ("no_update_assignees", models.JSONField(default=list)),
                ("resolved_by_assignee", models.JSONField(default=dict)),
                ("analytics_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="core.filter",
                    ),
                ),
            ],
            options={
                "ordering": ["-analytics_date"],
                "indexes": [
                    models.Index(
                        fields=["filter", "analytics_date"],
                        name="core_dailya_filter__11d021_idx",
                    )
                ],
            },
        ),
    ]
