# Generated by Django 4.2.11 on 2026-05-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsnapshot",
            name="issue_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
